/**
 * Seeded Permissions List for CRM and Marketing Modules
 *
 * This file contains permission metadata definitions for every endpoint in:
 * - CRM Module (Agent, Document, Lead Source, Lead, Opportunity, Segmentation)
 * - Marketing Module (Campaigns, Advertisements, Expenses, Daily Metrics, Attributions, Reports)
 *
 * Each permission object has a name, description, module, controller, method, and endpoint path.
 */

export interface SeededPermission {
  name: string;
  description: string;
  module: 'CRM' | 'Marketing';
  controller: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
}

export const SEEDED_PERMISSIONS: SeededPermission[] = [
  // =========================================================================
  // CRM MODULE ENDPOINTS
  // =========================================================================

  // --- 1. Agent Controller (Prefix: /api/agents) ---
  {
    name: 'crm.agents.read',
    description: 'Get all sales agents (active and inactive)',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents',
  },
  {
    name: 'crm.agents.create',
    description: 'Create a new sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'POST',
    path: '/api/agents',
  },
  {
    name: 'crm.agents.update',
    description: 'Update an existing sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/:id',
  },
  {
    name: 'crm.agents.delete',
    description: 'Deactivate / Soft-delete a sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'DELETE',
    path: '/api/agents/:id',
  },
  {
    name: 'crm.agents.metadata.read',
    description: 'Get CRM configuration metadata (agents, sources, statuses)',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents/metadata',
  },
  {
    name: 'crm.agents.reminders.read',
    description: 'Get pending followup reminders',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents/reminders',
  },
  {
    name: 'crm.agents.reminders.complete',
    description: 'Mark a followup reminder as completed',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/complete',
  },
  {
    name: 'crm.agents.reminders.snooze',
    description: 'Snooze a followup reminder by a given number of minutes',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/snooze',
  },
  {
    name: 'crm.agents.reminders.reschedule',
    description: 'Reschedule a followup reminder to a new datetime',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/reschedule',
  },
  {
    name: 'crm.agents.reminders.escalations.trigger',
    description: 'Trigger check of overdue reminders to escalate to managers',
    module: 'CRM',
    controller: 'AgentController',
    method: 'POST',
    path: '/api/agents/reminders/cron/check-escalations',
  },

  // --- 2. Document Controller (Prefix: /api/documents) ---
  {
    name: 'crm.documents.read_all',
    description: 'Get all customer documents with optional filtering',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents',
  },
  {
    name: 'crm.documents.read',
    description: 'Get details of a customer document and log access action',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id',
  },
  {
    name: 'crm.documents.versions.read',
    description: 'Get version history of a customer document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id/versions',
  },
  {
    name: 'crm.documents.access_logs.read',
    description: 'Get access log history of a customer document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id/access-logs',
  },
  {
    name: 'crm.documents.upload',
    description: 'Upload a new customer document for a lead',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/:leadId',
  },
  {
    name: 'crm.documents.add_version',
    description: 'Upload a new version of an existing document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/:id/version',
  },
  {
    name: 'crm.documents.expiry_check.trigger',
    description: 'Trigger validation check of document expiration dates and notify agents',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/cron/check-expiry',
  },

  // --- 3. Lead Source Controller (Prefix: /api/lead-sources) ---
  {
    name: 'crm.lead_sources.read_all',
    description: 'Get all lead sources',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'GET',
    path: '/api/lead-sources',
  },
  {
    name: 'crm.lead_sources.read',
    description: 'Get a lead source by ID',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'GET',
    path: '/api/lead-sources/:id',
  },
  {
    name: 'crm.lead_sources.create',
    description: 'Create a new lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'POST',
    path: '/api/lead-sources',
  },
  {
    name: 'crm.lead_sources.update',
    description: 'Update a lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'PUT',
    path: '/api/lead-sources/:id',
  },
  {
    name: 'crm.lead_sources.delete',
    description: 'Soft delete / deactivate a lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'DELETE',
    path: '/api/lead-sources/:id',
  },

  // --- 4. Lead Controller (Prefix: /api/leads) ---
  {
    name: 'crm.leads.create',
    description: 'Create a new lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads',
  },
  {
    name: 'crm.leads.read_all',
    description: 'Get all leads with optional filtering and pagination',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads',
  },
  {
    name: 'crm.leads.stats.read',
    description: 'Get lead statistics dashboard summary',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/stats',
  },
  {
    name: 'crm.leads.export',
    description: 'Export leads list to CSV format',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/export',
  },
  {
    name: 'crm.leads.notes.read_all',
    description: 'Get all internal notes across all leads',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/notes/all',
  },
  {
    name: 'crm.leads.attachments.read_all',
    description: 'Get all lead attachments/documents',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/attachments/all',
  },
  {
    name: 'crm.leads.activities.read_all',
    description: 'Get all lead activities/interactions',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/activities/all',
  },
  {
    name: 'crm.leads.read',
    description: 'Get a lead by ID including activities, contacts, and attachments',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id',
  },
  {
    name: 'crm.leads.update',
    description: 'Update an existing lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'PUT',
    path: '/api/leads/:id',
  },
  {
    name: 'crm.leads.assign',
    description: 'Assign a lead to a sales agent',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/assign',
  },
  {
    name: 'crm.leads.status.update',
    description: 'Change the status of a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/status',
  },
  {
    name: 'crm.leads.activities.create',
    description: 'Add a new activity log / interaction to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/activity',
  },
  {
    name: 'crm.leads.contacts.read',
    description: 'Get all additional contacts for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id/contacts',
  },
  {
    name: 'crm.leads.contacts.create',
    description: 'Add a new contact to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/contacts',
  },
  {
    name: 'crm.leads.attachments.upload',
    description: 'Upload a file attachment for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/attachments',
  },
  {
    name: 'crm.leads.attachments.read',
    description: 'Get all file attachments for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id/attachments',
  },
  {
    name: 'crm.leads.notes.create',
    description: 'Add a new internal note to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/notes',
  },

  // --- 5. Opportunity Controller (Prefix: /api/opportunities) ---
  {
    name: 'crm.opportunities.convert',
    description: 'Convert a Lead into an Opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/convert/:leadId',
  },
  {
    name: 'crm.opportunities.read_all',
    description: 'Get all opportunities with optional pagination and filtering',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities',
  },
  {
    name: 'crm.opportunities.metadata.read',
    description: 'Get metadata for opportunities (stages, loss reasons, agents)',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/metadata',
  },
  {
    name: 'crm.opportunities.forecast.read',
    description: 'Get expected revenue forecasting statistics',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/stats/forecast',
  },
  {
    name: 'crm.opportunities.read',
    description: 'Get details of an opportunity including activity logs and notes',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/:id',
  },
  {
    name: 'crm.opportunities.update',
    description: 'Update opportunity details',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'PUT',
    path: '/api/opportunities/:id',
  },
  {
    name: 'crm.opportunities.stage.update',
    description: 'Change the pipeline stage of an opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'PUT',
    path: '/api/opportunities/:id/stage',
  },
  {
    name: 'crm.opportunities.close_lost',
    description: 'Close the opportunity as Lost',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/close-lost',
  },
  {
    name: 'crm.opportunities.activities.create',
    description: 'Log a customer activity log for the opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/activity',
  },
  {
    name: 'crm.opportunities.notes.create',
    description: 'Log an internal note for the opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/notes',
  },

  // --- 6. Segmentation Controller (Prefix: /api/segments) ---
  {
    name: 'crm.segments.read_all',
    description: 'Get all segments with metadata (rule count and member count)',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments',
  },
  {
    name: 'crm.segments.tags.read_all',
    description: 'Get all lead tags',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments/tags',
  },
  {
    name: 'crm.segments.tags.create',
    description: 'Create a new lead tag',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments/tags',
  },
  {
    name: 'crm.segments.read',
    description: 'Get details of a segment including members and rules',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments/:id',
  },
  {
    name: 'crm.segments.create',
    description: 'Create a new segment and execute its rules',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments',
  },
  {
    name: 'crm.segments.recalculate',
    description: 'Recalculate dynamic segment members',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments/:id/recalculate',
  },
  {
    name: 'crm.segments.delete',
    description: 'Delete a customer segment',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'DELETE',
    path: '/api/segments/:id',
  },


  // =========================================================================
  // MARKETING MODULE ENDPOINTS
  // =========================================================================

  // --- 7. Marketing Controller (Prefix: /api/marketing) ---
  // --- Campaign Sub-endpoints ---
  {
    name: 'marketing.campaigns.read_all',
    description: 'Get all marketing campaigns',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns',
  },
  {
    name: 'marketing.campaigns.budgets.read',
    description: 'Get all campaign budget allocations',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns/budgets',
  },
  {
    name: 'marketing.campaigns.read',
    description: 'Get campaign details by ID',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns/:id',
  },
  {
    name: 'marketing.campaigns.create',
    description: 'Create a new marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/campaigns',
  },
  {
    name: 'marketing.campaigns.update',
    description: 'Update a marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'PUT',
    path: '/api/marketing/campaigns/:id',
  },
  {
    name: 'marketing.campaigns.delete',
    description: 'Delete a marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'DELETE',
    path: '/api/marketing/campaigns/:id',
  },

  // --- Advertisement Sub-endpoints ---
  {
    name: 'marketing.advertisements.read_all',
    description: 'Get all advertisements',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements',
  },
  {
    name: 'marketing.advertisements.read',
    description: 'Get advertisement details by ID',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id',
  },
  {
    name: 'marketing.advertisements.create',
    description: 'Register a new advertisement placement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements',
  },
  {
    name: 'marketing.advertisements.update',
    description: 'Update advertisement details',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'PUT',
    path: '/api/marketing/advertisements/:id',
  },
  {
    name: 'marketing.advertisements.delete',
    description: 'Delete advertisement placement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'DELETE',
    path: '/api/marketing/advertisements/:id',
  },

  // --- Ad Expenses Sub-endpoints ---
  {
    name: 'marketing.advertisements.expenses.read',
    description: 'Get expenses logged for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id/expenses',
  },
  {
    name: 'marketing.advertisements.expenses.create',
    description: 'Log an expense record for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements/:id/expenses',
  },

  // --- Ad Performances Sub-endpoints ---
  {
    name: 'marketing.advertisements.performances.read',
    description: 'Get performance logs for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id/performances',
  },
  {
    name: 'marketing.advertisements.performances.create',
    description: 'Record daily performance stats for an ad',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements/:id/performances',
  },

  // --- Lead Attribution Sub-endpoints ---
  {
    name: 'marketing.leads.read_all',
    description: 'Get all marketing lead attributions',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/leads',
  },
  {
    name: 'marketing.leads.track',
    description: 'Link CRM lead to marketing campaign / source',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/leads',
  },

  // --- Reports & Dashboards Sub-endpoints ---
  {
    name: 'marketing.reports.performance.read',
    description: 'Get campaign performance reports (view calculations)',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/performance',
  },
  {
    name: 'marketing.reports.lead_sources.read',
    description: 'Get lead source analysis reports (view calculations)',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/lead-sources',
  },
  {
    name: 'marketing.reports.dashboard.kpis.read',
    description: 'Get marketing dashboard executive KPIs summary',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/dashboard/kpis',
  },
  {
    name: 'marketing.reports.dashboard.charts.read',
    description: 'Get marketing dashboard chart historical metrics',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/dashboard/charts',
  },
];
