/**
 * Seeded Permissions List for CRM and Marketing Modules
 *
 * This file contains permission metadata definitions for every endpoint in:
 * - CRM Module (Agent, Document, Lead Source, Lead, Opportunity, Segmentation)
 * - Marketing Module (Campaigns, Advertisements, Expenses, Daily Metrics, Attributions, Reports)
 *
 * Each permission object has a name, description, module, controller, method, and endpoint path.
 */

export interface SeededPermission {
  name: string;
  description: string;
  module: 'CRM' | 'Marketing' | 'Property' | 'Sales' | 'Finance' | 'Broker';
  controller: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
}

export const SEEDED_PERMISSIONS: SeededPermission[] = [
  // =========================================================================
  // CRM MODULE ENDPOINTS
  // =========================================================================

  // --- 1. Agent Controller (Prefix: /api/agents) ---
  {
    name: 'crm.agents.read',
    description: 'Get all sales agents (active and inactive)',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents',
  },
  {
    name: 'crm.agents.create',
    description: 'Create a new sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'POST',
    path: '/api/agents',
  },
  {
    name: 'crm.agents.update',
    description: 'Update an existing sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/:id',
  },
  {
    name: 'crm.agents.delete',
    description: 'Deactivate / Soft-delete a sales agent',
    module: 'CRM',
    controller: 'AgentController',
    method: 'DELETE',
    path: '/api/agents/:id',
  },
  {
    name: 'crm.agents.metadata.read',
    description: 'Get CRM configuration metadata (agents, sources, statuses)',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents/metadata',
  },
  {
    name: 'crm.agents.reminders.read',
    description: 'Get pending followup reminders',
    module: 'CRM',
    controller: 'AgentController',
    method: 'GET',
    path: '/api/agents/reminders',
  },
  {
    name: 'crm.agents.reminders.complete',
    description: 'Mark a followup reminder as completed',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/complete',
  },
  {
    name: 'crm.agents.reminders.snooze',
    description: 'Snooze a followup reminder by a given number of minutes',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/snooze',
  },
  {
    name: 'crm.agents.reminders.reschedule',
    description: 'Reschedule a followup reminder to a new datetime',
    module: 'CRM',
    controller: 'AgentController',
    method: 'PUT',
    path: '/api/agents/reminders/:id/reschedule',
  },
  {
    name: 'crm.agents.reminders.escalations.trigger',
    description: 'Trigger check of overdue reminders to escalate to managers',
    module: 'CRM',
    controller: 'AgentController',
    method: 'POST',
    path: '/api/agents/reminders/cron/check-escalations',
  },

  // --- 2. Document Controller (Prefix: /api/documents) ---
  {
    name: 'crm.documents.read_all',
    description: 'Get all customer documents with optional filtering',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents',
  },
  {
    name: 'crm.documents.read',
    description: 'Get details of a customer document and log access action',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id',
  },
  {
    name: 'crm.documents.versions.read',
    description: 'Get version history of a customer document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id/versions',
  },
  {
    name: 'crm.documents.access_logs.read',
    description: 'Get access log history of a customer document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'GET',
    path: '/api/documents/:id/access-logs',
  },
  {
    name: 'crm.documents.upload',
    description: 'Upload a new customer document for a lead',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/:leadId',
  },
  {
    name: 'crm.documents.add_version',
    description: 'Upload a new version of an existing document',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/:id/version',
  },
  {
    name: 'crm.documents.expiry_check.trigger',
    description: 'Trigger validation check of document expiration dates and notify agents',
    module: 'CRM',
    controller: 'DocumentController',
    method: 'POST',
    path: '/api/documents/cron/check-expiry',
  },

  // --- 3. Lead Source Controller (Prefix: /api/lead-sources) ---
  {
    name: 'crm.lead_sources.read_all',
    description: 'Get all lead sources',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'GET',
    path: '/api/lead-sources',
  },
  {
    name: 'crm.lead_sources.read',
    description: 'Get a lead source by ID',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'GET',
    path: '/api/lead-sources/:id',
  },
  {
    name: 'crm.lead_sources.create',
    description: 'Create a new lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'POST',
    path: '/api/lead-sources',
  },
  {
    name: 'crm.lead_sources.update',
    description: 'Update a lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'PUT',
    path: '/api/lead-sources/:id',
  },
  {
    name: 'crm.lead_sources.delete',
    description: 'Soft delete / deactivate a lead source',
    module: 'CRM',
    controller: 'LeadSourceController',
    method: 'DELETE',
    path: '/api/lead-sources/:id',
  },

  // --- 4. Lead Controller (Prefix: /api/leads) ---
  {
    name: 'crm.leads.create',
    description: 'Create a new lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads',
  },
  {
    name: 'crm.leads.read_all',
    description: 'Get all leads with optional filtering and pagination',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads',
  },
  {
    name: 'crm.leads.stats.read',
    description: 'Get lead statistics dashboard summary',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/stats',
  },
  {
    name: 'crm.leads.export',
    description: 'Export leads list to CSV format',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/export',
  },
  {
    name: 'crm.leads.notes.read_all',
    description: 'Get all internal notes across all leads',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/notes/all',
  },
  {
    name: 'crm.leads.attachments.read_all',
    description: 'Get all lead attachments/documents',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/attachments/all',
  },
  {
    name: 'crm.leads.activities.read_all',
    description: 'Get all lead activities/interactions',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/activities/all',
  },
  {
    name: 'crm.leads.read',
    description: 'Get a lead by ID including activities, contacts, and attachments',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id',
  },
  {
    name: 'crm.leads.update',
    description: 'Update an existing lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'PUT',
    path: '/api/leads/:id',
  },
  {
    name: 'crm.leads.assign',
    description: 'Assign a lead to a sales agent',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/assign',
  },
  {
    name: 'crm.leads.status.update',
    description: 'Change the status of a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/status',
  },
  {
    name: 'crm.leads.activities.create',
    description: 'Add a new activity log / interaction to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/activity',
  },
  {
    name: 'crm.leads.contacts.read',
    description: 'Get all additional contacts for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id/contacts',
  },
  {
    name: 'crm.leads.contacts.create',
    description: 'Add a new contact to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/contacts',
  },
  {
    name: 'crm.leads.attachments.upload',
    description: 'Upload a file attachment for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/attachments',
  },
  {
    name: 'crm.leads.attachments.read',
    description: 'Get all file attachments for a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'GET',
    path: '/api/leads/:id/attachments',
  },
  {
    name: 'crm.leads.notes.create',
    description: 'Add a new internal note to a lead',
    module: 'CRM',
    controller: 'LeadController',
    method: 'POST',
    path: '/api/leads/:id/notes',
  },

  // --- 5. Opportunity Controller (Prefix: /api/opportunities) ---
  {
    name: 'crm.opportunities.convert',
    description: 'Convert a Lead into an Opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/convert/:leadId',
  },
  {
    name: 'crm.opportunities.read_all',
    description: 'Get all opportunities with optional pagination and filtering',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities',
  },
  {
    name: 'crm.opportunities.metadata.read',
    description: 'Get metadata for opportunities (stages, loss reasons, agents)',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/metadata',
  },
  {
    name: 'crm.opportunities.forecast.read',
    description: 'Get expected revenue forecasting statistics',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/stats/forecast',
  },
  {
    name: 'crm.opportunities.read',
    description: 'Get details of an opportunity including activity logs and notes',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'GET',
    path: '/api/opportunities/:id',
  },
  {
    name: 'crm.opportunities.update',
    description: 'Update opportunity details',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'PUT',
    path: '/api/opportunities/:id',
  },
  {
    name: 'crm.opportunities.stage.update',
    description: 'Change the pipeline stage of an opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'PUT',
    path: '/api/opportunities/:id/stage',
  },
  {
    name: 'crm.opportunities.close_lost',
    description: 'Close the opportunity as Lost',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/close-lost',
  },
  {
    name: 'crm.opportunities.activities.create',
    description: 'Log a customer activity log for the opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/activity',
  },
  {
    name: 'crm.opportunities.notes.create',
    description: 'Log an internal note for the opportunity',
    module: 'CRM',
    controller: 'OpportunityController',
    method: 'POST',
    path: '/api/opportunities/:id/notes',
  },

  // --- 6. Segmentation Controller (Prefix: /api/segments) ---
  {
    name: 'crm.segments.read_all',
    description: 'Get all segments with metadata (rule count and member count)',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments',
  },
  {
    name: 'crm.segments.tags.read_all',
    description: 'Get all lead tags',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments/tags',
  },
  {
    name: 'crm.segments.tags.create',
    description: 'Create a new lead tag',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments/tags',
  },
  {
    name: 'crm.segments.read',
    description: 'Get details of a segment including members and rules',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'GET',
    path: '/api/segments/:id',
  },
  {
    name: 'crm.segments.create',
    description: 'Create a new segment and execute its rules',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments',
  },
  {
    name: 'crm.segments.recalculate',
    description: 'Recalculate dynamic segment members',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'POST',
    path: '/api/segments/:id/recalculate',
  },
  {
    name: 'crm.segments.delete',
    description: 'Delete a customer segment',
    module: 'CRM',
    controller: 'SegmentationController',
    method: 'DELETE',
    path: '/api/segments/:id',
  },


  // =========================================================================
  // MARKETING MODULE ENDPOINTS
  // =========================================================================

  // --- 7. Marketing Controller (Prefix: /api/marketing) ---
  // --- Campaign Sub-endpoints ---
  {
    name: 'marketing.campaigns.read_all',
    description: 'Get all marketing campaigns',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns',
  },
  {
    name: 'marketing.campaigns.budgets.read',
    description: 'Get all campaign budget allocations',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns/budgets',
  },
  {
    name: 'marketing.campaigns.read',
    description: 'Get campaign details by ID',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/campaigns/:id',
  },
  {
    name: 'marketing.campaigns.create',
    description: 'Create a new marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/campaigns',
  },
  {
    name: 'marketing.campaigns.update',
    description: 'Update a marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'PUT',
    path: '/api/marketing/campaigns/:id',
  },
  {
    name: 'marketing.campaigns.delete',
    description: 'Delete a marketing campaign',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'DELETE',
    path: '/api/marketing/campaigns/:id',
  },

  // --- Advertisement Sub-endpoints ---
  {
    name: 'marketing.advertisements.read_all',
    description: 'Get all advertisements',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements',
  },
  {
    name: 'marketing.advertisements.read',
    description: 'Get advertisement details by ID',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id',
  },
  {
    name: 'marketing.advertisements.create',
    description: 'Register a new advertisement placement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements',
  },
  {
    name: 'marketing.advertisements.update',
    description: 'Update advertisement details',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'PUT',
    path: '/api/marketing/advertisements/:id',
  },
  {
    name: 'marketing.advertisements.delete',
    description: 'Delete advertisement placement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'DELETE',
    path: '/api/marketing/advertisements/:id',
  },

  // --- Ad Expenses Sub-endpoints ---
  {
    name: 'marketing.advertisements.expenses.read',
    description: 'Get expenses logged for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id/expenses',
  },
  {
    name: 'marketing.advertisements.expenses.create',
    description: 'Log an expense record for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements/:id/expenses',
  },

  // --- Ad Performances Sub-endpoints ---
  {
    name: 'marketing.advertisements.performances.read',
    description: 'Get performance logs for an advertisement',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/advertisements/:id/performances',
  },
  {
    name: 'marketing.advertisements.performances.create',
    description: 'Record daily performance stats for an ad',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/advertisements/:id/performances',
  },

  // --- Lead Attribution Sub-endpoints ---
  {
    name: 'marketing.leads.read_all',
    description: 'Get all marketing lead attributions',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/leads',
  },
  {
    name: 'marketing.leads.track',
    description: 'Link CRM lead to marketing campaign / source',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'POST',
    path: '/api/marketing/leads',
  },

  // --- Reports & Dashboards Sub-endpoints ---
  {
    name: 'marketing.reports.performance.read',
    description: 'Get campaign performance reports (view calculations)',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/performance',
  },
  {
    name: 'marketing.reports.lead_sources.read',
    description: 'Get lead source analysis reports (view calculations)',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/lead-sources',
  },
  {
    name: 'marketing.reports.dashboard.kpis.read',
    description: 'Get marketing dashboard executive KPIs summary',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/dashboard/kpis',
  },
  {
    name: 'marketing.reports.dashboard.charts.read',
    description: 'Get marketing dashboard chart historical metrics',
    module: 'Marketing',
    controller: 'MarketingController',
    method: 'GET',
    path: '/api/marketing/reports/dashboard/charts',
  },

  // =========================================================================
  // PROPERTY MODULE ENDPOINTS
  // =========================================================================

  // --- 8. Properties Controller (Prefix: /api/properties) ---
  {
    name: 'properties.create',
    description: 'Create a new property',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'POST',
    path: '/api/properties',
  },
  {
    name: 'properties.read',
    description: 'Get all properties with optional query filters',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'GET',
    path: '/api/properties',
  },
  {
    name: 'properties.read_one',
    description: 'Get a single property by ID',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'GET',
    path: '/api/properties/:id',
  },
  {
    name: 'properties.update',
    description: 'Update an existing property',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'PUT',
    path: '/api/properties/:id',
  },
  {
    name: 'properties.delete',
    description: 'Delete/remove a property',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'DELETE',
    path: '/api/properties/:id',
  },
  {
    name: 'properties.buildings.create',
    description: 'Create a building under a property',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'POST',
    path: '/api/properties/:id/buildings',
  },
  {
    name: 'properties.buildings.read',
    description: 'Get a single building details',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'GET',
    path: '/api/properties/buildings/:id',
  },
  {
    name: 'properties.buildings.update',
    description: 'Update a building',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'PUT',
    path: '/api/properties/buildings/:id',
  },
  {
    name: 'properties.buildings.delete',
    description: 'Remove a building',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'DELETE',
    path: '/api/properties/buildings/:id',
  },
  {
    name: 'properties.floors.create',
    description: 'Create a floor under a building',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'POST',
    path: '/api/properties/buildings/:id/floors',
  },
  {
    name: 'properties.floors.update',
    description: 'Update a floor',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'PUT',
    path: '/api/properties/floors/:id',
  },
  {
    name: 'properties.floors.delete',
    description: 'Remove a floor',
    module: 'Property',
    controller: 'PropertiesController',
    method: 'DELETE',
    path: '/api/properties/floors/:id',
  },

  // --- 9. Units Controller (Prefix: /api/units) ---
  {
    name: 'properties.units.create',
    description: 'Create a new unit',
    module: 'Property',
    controller: 'UnitsController',
    method: 'POST',
    path: '/api/units',
  },
  {
    name: 'properties.units.read',
    description: 'Find all units with query filtering',
    module: 'Property',
    controller: 'UnitsController',
    method: 'GET',
    path: '/api/units',
  },
  {
    name: 'properties.units.status_history.read',
    description: 'Get unit status history',
    module: 'Property',
    controller: 'UnitsController',
    method: 'GET',
    path: '/api/units/status-history',
  },
  {
    name: 'properties.units.read_one',
    description: 'Get details of a unit by ID',
    module: 'Property',
    controller: 'UnitsController',
    method: 'GET',
    path: '/api/units/:id',
  },
  {
    name: 'properties.units.update',
    description: 'Update an existing unit',
    module: 'Property',
    controller: 'UnitsController',
    method: 'PUT',
    path: '/api/units/:id',
  },
  {
    name: 'properties.units.delete',
    description: 'Remove a unit',
    module: 'Property',
    controller: 'UnitsController',
    method: 'DELETE',
    path: '/api/units/:id',
  },
  {
    name: 'properties.units.status.update',
    description: 'Transition a unit status',
    module: 'Property',
    controller: 'UnitsController',
    method: 'PUT',
    path: '/api/units/:id/status',
  },
  {
    name: 'properties.units.import',
    description: 'Bulk import units via CSV file',
    module: 'Property',
    controller: 'UnitsController',
    method: 'POST',
    path: '/api/units/import',
  },

  // --- 10. Sites Controller (Prefix: /api/properties) ---
  {
    name: 'properties.sites.create',
    description: 'Create a site under a property',
    module: 'Property',
    controller: 'SitesController',
    method: 'POST',
    path: '/api/properties/:propertyId/sites',
  },
  {
    name: 'properties.sites.read',
    description: 'Get all sites under a property',
    module: 'Property',
    controller: 'SitesController',
    method: 'GET',
    path: '/api/properties/:propertyId/sites',
  },
  {
    name: 'properties.sites.read_one',
    description: 'Get a single site details',
    module: 'Property',
    controller: 'SitesController',
    method: 'GET',
    path: '/api/properties/sites/:id',
  },
  {
    name: 'properties.sites.update',
    description: 'Update site details',
    module: 'Property',
    controller: 'SitesController',
    method: 'PUT',
    path: '/api/properties/sites/:id',
  },
  {
    name: 'properties.sites.delete',
    description: 'Remove a site',
    module: 'Property',
    controller: 'SitesController',
    method: 'DELETE',
    path: '/api/properties/sites/:id',
  },

  // --- 11. Property Types Controller (Prefix: /api/property-types) ---
  {
    name: 'properties.property_types.create',
    description: 'Create a new property type',
    module: 'Property',
    controller: 'PropertyTypesController',
    method: 'POST',
    path: '/api/property-types',
  },
  {
    name: 'properties.property_types.read',
    description: 'Get all property types',
    module: 'Property',
    controller: 'PropertyTypesController',
    method: 'GET',
    path: '/api/property-types',
  },
  {
    name: 'properties.property_types.read_one',
    description: 'Get a single property type',
    module: 'Property',
    controller: 'PropertyTypesController',
    method: 'GET',
    path: '/api/property-types/:id',
  },
  {
    name: 'properties.property_types.update',
    description: 'Update a property type',
    module: 'Property',
    controller: 'PropertyTypesController',
    method: 'PUT',
    path: '/api/property-types/:id',
  },
  {
    name: 'properties.property_types.delete',
    description: 'Remove a property type',
    module: 'Property',
    controller: 'PropertyTypesController',
    method: 'DELETE',
    path: '/api/property-types/:id',
  },

  // --- 12. Unit Types Controller (Prefix: /api/unit-types) ---
  {
    name: 'properties.unit_types.create',
    description: 'Create a new unit type',
    module: 'Property',
    controller: 'UnitTypesController',
    method: 'POST',
    path: '/api/unit-types',
  },
  {
    name: 'properties.unit_types.read',
    description: 'Get all unit types',
    module: 'Property',
    controller: 'UnitTypesController',
    method: 'GET',
    path: '/api/unit-types',
  },
  {
    name: 'properties.unit_types.read_one',
    description: 'Get a single unit type',
    module: 'Property',
    controller: 'UnitTypesController',
    method: 'GET',
    path: '/api/unit-types/:id',
  },
  {
    name: 'properties.unit_types.update',
    description: 'Update a unit type',
    module: 'Property',
    controller: 'UnitTypesController',
    method: 'PUT',
    path: '/api/unit-types/:id',
  },
  {
    name: 'properties.unit_types.delete',
    description: 'Remove a unit type',
    module: 'Property',
    controller: 'UnitTypesController',
    method: 'DELETE',
    path: '/api/unit-types/:id',
  },

  // --- 13. Unit Statuses Controller (Prefix: /api/unit-statuses) ---
  {
    name: 'properties.unit_statuses.read',
    description: 'Get all unit statuses',
    module: 'Property',
    controller: 'UnitStatusesController',
    method: 'GET',
    path: '/api/unit-statuses',
  },
  {
    name: 'properties.unit_statuses.update',
    description: 'Update a unit status config',
    module: 'Property',
    controller: 'UnitStatusesController',
    method: 'PUT',
    path: '/api/unit-statuses/:id',
  },

  // --- 14. Amenities Controller (Prefix: /api/amenities) ---
  {
    name: 'properties.amenities.create',
    description: 'Create a new amenity',
    module: 'Property',
    controller: 'AmenitiesController',
    method: 'POST',
    path: '/api/amenities',
  },
  {
    name: 'properties.amenities.read',
    description: 'Get all amenities',
    module: 'Property',
    controller: 'AmenitiesController',
    method: 'GET',
    path: '/api/amenities',
  },
  {
    name: 'properties.amenities.read_one',
    description: 'Get details of an amenity',
    module: 'Property',
    controller: 'AmenitiesController',
    method: 'GET',
    path: '/api/amenities/:id',
  },
  {
    name: 'properties.amenities.update',
    description: 'Update an amenity',
    module: 'Property',
    controller: 'AmenitiesController',
    method: 'PUT',
    path: '/api/amenities/:id',
  },
  {
    name: 'properties.amenities.delete',
    description: 'Remove an amenity',
    module: 'Property',
    controller: 'AmenitiesController',
    method: 'DELETE',
    path: '/api/amenities/:id',
  },

  // --- 15. Pricing Controller (Prefix: /api/unit-prices) ---
  {
    name: 'properties.pricing.create',
    description: 'Create unit pricing configuration',
    module: 'Property',
    controller: 'PricingController',
    method: 'POST',
    path: '/api/unit-prices',
  },
  {
    name: 'properties.pricing.promotions.create',
    description: 'Create a pricing promotion',
    module: 'Property',
    controller: 'PricingController',
    method: 'POST',
    path: '/api/unit-prices/promotions',
  },
  {
    name: 'properties.pricing.promotions.read_active',
    description: 'Get active pricing promotions',
    module: 'Property',
    controller: 'PricingController',
    method: 'GET',
    path: '/api/unit-prices/promotions/active',
  },
  {
    name: 'properties.pricing.promotions.read',
    description: 'Get all promotions',
    module: 'Property',
    controller: 'PricingController',
    method: 'GET',
    path: '/api/unit-prices/promotions',
  },
  {
    name: 'properties.pricing.promotions.update',
    description: 'Update a promotion',
    module: 'Property',
    controller: 'PricingController',
    method: 'PUT',
    path: '/api/unit-prices/promotions/:id',
  },
  {
    name: 'properties.pricing.promotions.deactivate',
    description: 'Deactivate a promotion',
    module: 'Property',
    controller: 'PricingController',
    method: 'PATCH',
    path: '/api/unit-prices/promotions/:id/deactivate',
  },

  // --- 16. Media Controller (Prefix: /api/property-media) ---
  {
    name: 'properties.media.upload',
    description: 'Upload property media files',
    module: 'Property',
    controller: 'MediaController',
    method: 'POST',
    path: '/api/property-media',
  },
  {
    name: 'properties.media.documents.upload',
    description: 'Upload property documents',
    module: 'Property',
    controller: 'MediaController',
    method: 'POST',
    path: '/api/property-media/documents',
  },
  {
    name: 'properties.media.floorplans.upload',
    description: 'Upload floor plans',
    module: 'Property',
    controller: 'MediaController',
    method: 'POST',
    path: '/api/property-media/floorplans',
  },

  // --- 17. Dashboard Controller (Prefix: /api/inventory/dashboard) ---
  {
    name: 'properties.dashboard.read',
    description: 'Get inventory statistics dashboard summary',
    module: 'Property',
    controller: 'DashboardController',
    method: 'GET',
    path: '/api/inventory/dashboard',
  },


  // =========================================================================
  // SALES MODULE ENDPOINTS
  // =========================================================================

  // --- 18. Sales Controller (Prefix: /api/sales) ---
  {
    name: 'sales.customers.create',
    description: 'Create a new customer profile',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/customers',
  },
  {
    name: 'sales.customers.read',
    description: 'Get all customer profiles',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/customers',
  },
  {
    name: 'sales.customers.read_one',
    description: 'Get details of a customer profile by ID',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/customers/:id',
  },
  {
    name: 'sales.customers.update',
    description: 'Update customer profile details',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/customers/:id',
  },
  {
    name: 'sales.customers.delete',
    description: 'Delete customer profile',
    module: 'Sales',
    controller: 'SalesController',
    method: 'DELETE',
    path: '/api/sales/customers/:id',
  },
  {
    name: 'sales.reservations.create',
    description: 'Create unit sales reservation',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/reservations',
  },
  {
    name: 'sales.reservations.read',
    description: 'Get all sales reservations',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/reservations',
  },
  {
    name: 'sales.reservations.extend',
    description: 'Extend sales reservation duration',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/reservations/extend',
  },
  {
    name: 'sales.reservations.process_expired',
    description: 'Trigger sweeper process for expired reservations',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/reservations/process-expired',
  },
  {
    name: 'sales.reservations.cancel',
    description: 'Cancel unit sales reservation',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/reservations/:id/cancel',
  },
  {
    name: 'sales.pricing.calculate',
    description: 'Calculate property/unit quotation price based on configuration',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/pricing/calculate',
  },
  {
    name: 'sales.quotations.create',
    description: 'Create a new quotation',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/quotations',
  },
  {
    name: 'sales.quotations.read',
    description: 'Get all sales quotations',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/quotations',
  },
  {
    name: 'sales.bookings.create',
    description: 'Create a new sales booking',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/bookings',
  },
  {
    name: 'sales.bookings.read',
    description: 'Get all sales bookings',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/bookings',
  },
  {
    name: 'sales.bookings.approve',
    description: 'Approve a sales booking',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/bookings/:id/approve',
  },
  {
    name: 'sales.bookings.cancel',
    description: 'Cancel a sales booking',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/bookings/:id/cancel',
  },
  {
    name: 'sales.agreements.create',
    description: 'Create sales booking agreement',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/agreements',
  },
  {
    name: 'sales.agreements.read',
    description: 'Get all sales booking agreements',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/agreements',
  },
  {
    name: 'sales.contracts.create',
    description: 'Create sales contract',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/contracts',
  },
  {
    name: 'sales.contracts.read',
    description: 'Get all sales contracts',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/contracts',
  },
  {
    name: 'sales.contracts.documents.create',
    description: 'Link contract document metadata',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/contracts/:id/document',
  },
  {
    name: 'sales.contracts.documents.upload',
    description: 'Upload file attachment as contract document',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/contracts/:id/document/upload',
  },
  {
    name: 'sales.contracts.documents.delete',
    description: 'Remove contract document attachment',
    module: 'Sales',
    controller: 'SalesController',
    method: 'DELETE',
    path: '/api/sales/contracts/documents/:id',
  },
  {
    name: 'sales.installments.plan.create',
    description: 'Generate installment plan outline',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/installments/plan',
  },
  {
    name: 'sales.installments.plans.read',
    description: 'Get list of installment plans',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/installments/plans',
  },
  {
    name: 'sales.installments.pay',
    description: 'Record installment schedule payment collection update',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/installments/schedules/:id/pay',
  },
  {
    name: 'sales.discounts.create',
    description: 'Create discount approval request',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/discounts',
  },
  {
    name: 'sales.discounts.read',
    description: 'Get all discount approval requests',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/discounts',
  },
  {
    name: 'sales.discounts.approve',
    description: 'Approve discount request',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/discounts/:id/approve',
  },
  {
    name: 'sales.discounts.reject',
    description: 'Reject discount request',
    module: 'Sales',
    controller: 'SalesController',
    method: 'PUT',
    path: '/api/sales/discounts/:id/reject',
  },
  {
    name: 'sales.commissions.rules.create',
    description: 'Create sales commission calculation rule',
    module: 'Sales',
    controller: 'SalesController',
    method: 'POST',
    path: '/api/sales/commissions/rules',
  },
  {
    name: 'sales.commissions.rules.read',
    description: 'Get all sales commission rules',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/commissions/rules',
  },
  {
    name: 'sales.commissions.read',
    description: 'Get logged sales commissions',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/commissions',
  },
  {
    name: 'sales.dashboard.read',
    description: 'Get sales executive dashboard summary metrics',
    module: 'Sales',
    controller: 'SalesController',
    method: 'GET',
    path: '/api/sales/dashboard/stats',
  },


  // =========================================================================
  // FINANCE MODULE ENDPOINTS
  // =========================================================================

  // --- 19. Finance Controller (Prefix: /api/finance) ---
  {
    name: 'finance.payment_methods.read',
    description: 'Get all supported payment methods',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/payment-methods',
  },
  {
    name: 'finance.payment_methods.create',
    description: 'Register a new payment method configuration',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/payment-methods',
  },
  {
    name: 'finance.payments.create',
    description: 'Submit a new payment transaction entry',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/payments',
  },
  {
    name: 'finance.payments.read',
    description: 'Get all payment transaction ledger records',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/payments',
  },
  {
    name: 'finance.payments.read_one',
    description: 'Get a single payment transaction details',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/payments/:id',
  },
  {
    name: 'finance.payments.approve',
    description: 'Approve a pending payment and generate receipt',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'PUT',
    path: '/api/finance/payments/:id/approve',
  },
  {
    name: 'finance.payments.reject',
    description: 'Reject a pending payment transaction',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'PUT',
    path: '/api/finance/payments/:id/reject',
  },
  {
    name: 'finance.payments.reverse',
    description: 'Reverse an approved payment transaction',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'PUT',
    path: '/api/finance/payments/:id/reverse',
  },
  {
    name: 'finance.installments.reschedule',
    description: 'Reschedule an installment schedule due date and amount',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'PUT',
    path: '/api/finance/installments/:id/reschedule',
  },
  {
    name: 'finance.penalties.config.read',
    description: 'Get penalty calculation rule configurations',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/penalties/config',
  },
  {
    name: 'finance.penalties.config.create',
    description: 'Create or update penalty config rules',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/penalties/config',
  },
  {
    name: 'finance.penalties.config.delete',
    description: 'Remove penalty configuration rule',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'DELETE',
    path: '/api/finance/penalties/config/:id',
  },
  {
    name: 'finance.penalties.calculate_daily',
    description: 'Trigger check/calculation sweeper for late installment penalties',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/penalties/calculate-daily',
  },
  {
    name: 'finance.penalties.transactions.read',
    description: 'Get all penalty calculation history transactions',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/penalties/transactions',
  },
  {
    name: 'finance.penalties.waive',
    description: 'Waive or reduce calculated penalties for customer',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/penalties/waive/:id',
  },
  {
    name: 'finance.receipt_templates.read',
    description: 'Get receipt template configurations',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/receipt-templates',
  },
  {
    name: 'finance.receipt_templates.update',
    description: 'Update custom receipt layout configuration template',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'PUT',
    path: '/api/finance/receipt-templates/:id',
  },
  {
    name: 'finance.receipts.read',
    description: 'Get list of generated payment receipts',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/receipts',
  },
  {
    name: 'finance.receipts.reprint',
    description: 'Record receipt reprint action',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/receipts/:id/reprint',
  },
  {
    name: 'finance.balances.read',
    description: 'Get summary ledger of customer outstanding balances',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/balances',
  },
  {
    name: 'finance.statements.customer.read',
    description: 'Get complete customer account financial statements ledger',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/statements/customer/:customerId',
  },
  {
    name: 'finance.reports.aging.read',
    description: 'Get aging analysis collections report metrics',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/reports/aging',
  },
  {
    name: 'finance.reports.collections.read',
    description: 'Get revenue and collection reports analytical metrics',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/reports/collections',
  },
  {
    name: 'finance.reminders.config.read',
    description: 'Get payment reminder configuration settings',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/reminders/config',
  },
  {
    name: 'finance.reminders.config.update',
    description: 'Update payment reminder scheduler configuration settings',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/reminders/config',
  },
  {
    name: 'finance.reminders.logs.read',
    description: 'Get automated reminder delivery log records',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/reminders/logs',
  },
  {
    name: 'finance.reminders.trigger',
    description: 'Trigger check/delivery of payment outstanding reminders',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/reminders/trigger',
  },
  {
    name: 'finance.settings.read',
    description: 'Get global financial configuration settings',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/settings',
  },
  {
    name: 'finance.settings.update',
    description: 'Update global financial organization configuration settings',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/settings',
  },
  {
    name: 'finance.signature.read',
    description: 'Get signature PNG base64 for active user signature authorization',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'GET',
    path: '/api/finance/users/signature',
  },
  {
    name: 'finance.signature.update',
    description: 'Update signature PNG base64 configuration setting',
    module: 'Finance',
    controller: 'FinanceController',
    method: 'POST',
    path: '/api/finance/users/signature',
  },

  // =========================================================================
  // BROKER MODULE ENDPOINTS
  // =========================================================================
  {
    name: 'broker.dashboard.read',
    description: 'Get overall broker dashboard metrics & leaderboard',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/dashboard',
  },
  {
    name: 'broker.brokers.read',
    description: 'Get all brokers list',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers',
  },
  {
    name: 'broker.commission_plans.read_all',
    description: 'Get all commission plans',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/commission-plans/all',
  },
  {
    name: 'broker.commission_plans.read_one',
    description: 'Get commission plan by ID',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/commission-plans/:id',
  },
  {
    name: 'broker.sales.read_all',
    description: 'Get all attributable sales',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/sales/all',
  },
  {
    name: 'broker.commissions.read_all',
    description: 'Get all calculated broker commissions',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/commissions/all',
  },
  {
    name: 'broker.payments.read_all',
    description: 'Get all payouts logged',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/payments/all',
  },
  {
    name: 'broker.brokers.read_one',
    description: 'Get broker profile details',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/:id',
  },
  {
    name: 'broker.brokers.create',
    description: 'Onboard a new broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers',
  },
  {
    name: 'broker.brokers.update',
    description: 'Update broker profile',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'PUT',
    path: '/api/brokers/:id',
  },
  {
    name: 'broker.brokers.delete',
    description: 'Deactivate broker profile',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'DELETE',
    path: '/api/brokers/:id',
  },
  {
    name: 'broker.bank_accounts.create',
    description: 'Add bank payment details for a broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/:id/bank-accounts',
  },
  {
    name: 'broker.bank_accounts.delete',
    description: 'Remove bank payment details',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'DELETE',
    path: '/api/brokers/:id/bank-accounts/:accountId',
  },
  {
    name: 'broker.documents.upload',
    description: 'Upload broker licensing or identity document',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/:id/documents',
  },
  {
    name: 'broker.documents.delete',
    description: 'Remove broker document',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'DELETE',
    path: '/api/brokers/:id/documents/:docId',
  },
  {
    name: 'broker.project_assignments.create',
    description: 'Assign a broker to a property / project',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/:id/projects',
  },
  {
    name: 'broker.project_assignments.delete',
    description: 'Deassign a project from a broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'DELETE',
    path: '/api/brokers/:id/projects/:assignmentId',
  },
  {
    name: 'broker.lead_assignments.create',
    description: 'Assign a CRM lead to a broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/:id/leads',
  },
  {
    name: 'broker.lead_assignments.delete',
    description: 'Remove lead assignment',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'DELETE',
    path: '/api/brokers/:id/leads/:assignmentId',
  },
  {
    name: 'broker.commission_plans.create',
    description: 'Create a new commission plan',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/commission-plans',
  },
  {
    name: 'broker.project_commission_plans.create',
    description: 'Map a commission plan to a project',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/commission-plans/projects',
  },
  {
    name: 'broker.project_commission_plans.read',
    description: 'Get commission plan mapping for a specific project',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/commission-plans/projects/:propertyId',
  },
  {
    name: 'broker.sales.create',
    description: 'Attribute a sale to a broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/sales',
  },
  {
    name: 'broker.commissions.approve',
    description: 'Approve a calculated commission',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/commissions/:id/approve',
  },
  {
    name: 'broker.commissions.adjust',
    description: 'Record manual commission increase or decrease',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/commissions/:id/adjust',
  },
  {
    name: 'broker.payments.create',
    description: 'Record payment disbursements',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/payments',
  },
  {
    name: 'broker.targets.create',
    description: 'Configure targets for a broker',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'POST',
    path: '/api/brokers/:id/targets',
  },
  {
    name: 'broker.targets.read',
    description: 'Get targets historical configuration',
    module: 'Broker',
    controller: 'BrokerController',
    method: 'GET',
    path: '/api/brokers/:id/targets',
  },
];
